{
 "title": "Observe",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Observability",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "# Three Pillars\n1. Metrics\n2. Tracing\n3. Logs\n\n# Four Golden Signals\n\n1. Throughput\n2. Latency\n3. Error rate\n4. Saturation"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 0 },
   "options": {
    "content": "        .,*/(#####(/*,.                               .,*((###(/*.\n    .*(%%%%%%%%%%%%%%#/.                           .*#%%%%####%%%%#/.\n  ./#%%%%#(/,,...,,***.           .......          *#%%%#*.   ,(%%%#/.\n .(#%%%#/.                    .*(#%%%%%%%##/,.     ,(%%%#*    ,(%%%#*.\n.*#%%%#/.    ..........     .*#%%%%#(/((#%%%%(,     ,/#%%%#(/#%%%#(,\n./#%%%(*    ,#%%%%%%%%(*   .*#%%%#*     .*#%%%#,      *(%%%%%%%#(,.\n./#%%%#*    ,(((##%%%%(*   ,/%%%%/.      .(%%%#/   .*#%%%#(*/(#%%%#/,\n ,#%%%#(.        ,#%%%(*   ,/%%%%/.      .(%%%#/  ,/%%%#/.    .*#%%%(,\n  *#%%%%(*.      ,#%%%(*   .*#%%%#*     ./#%%%#,  ,(%%%#*      .(%%%#*\n   ,(#%%%%%##(((##%%%%(*    .*#%%%%#(((##%%%%(,   .*#%%%##(///(#%%%#/.\n     .*/###%%%%%%%###(/,      .,/##%%%%%##(/,.      .*(##%%%%%%##(*,\n          .........                ......                ......."
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"node_exporter:9100\",job=\"otel-collector\"} - node_boot_time_seconds{instance=\"node_exporter:9100\",job=\"otel-collector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "service": "go8" }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"otel-collector\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"otel-collector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.status" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"otel-collector\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"otel-collector\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{instance=\"node_exporter:9100\",job=\"otel-collector\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{instance=\"node_exporter:9100\",job=\"otel-collector\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\",job=\"otel-collector\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"otel-collector\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (rate({container=\"go8_container\"} | json | level =~`WARN|ERROR|FATAL` [5m]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 25, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "{container=\"go8_container\"} |= ``"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_count{}[1m])\n/\nrate(http_server_duration_sum{}[1m])",
     "legendFormat": "{{http_method}} {{http_status_code}} {{http_route}} "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (route_host_name) (rate(http_server_duration_count[$__interval]))",
     "legendFormat": "{{http_method}} {{http_status_code}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"node_exporter:9100\",job=\"otel-collector\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"node_exporter:9100\",job=\"otel-collector\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  }
 ]
}