// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Authors     string
	BookAuthors string
	Books       string
}{
	Authors:     "authors",
	BookAuthors: "book_authors",
	Books:       "books",
}
