version: '3.8'

services:

  postgres:
    image: "postgres:17"
    container_name: "go8_postgres_e2e"
    restart: "no"
    healthcheck:
      test: pg_isready -U go8_e2e_user
    environment:
      POSTGRES_USER: go8_e2e_user
      POSTGRES_PASSWORD: go8_e2e_pass
      POSTGRES_DB: go8_e2e_db

  server:
    image: "go8/server_test"
    container_name: "go8_server_e2e"
    restart: "no"
    build:
      context: ../
      dockerfile: e2e/server.Dockerfile
    entrypoint: ["/usr/local/bin/server"]
    environment:
      - DB_USER=go8_e2e_user
      - DB_PASS=go8_e2e_pass
      - DB_NAME=go8_e2e_db
      - REDIS_HOST=valkey
    depends_on:
      - postgres
      - migrate
      - valkey

  valkey:
    image: 'valkey/valkey:7.2'
    container_name: "go8_redis_e2e"
    restart: "no"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  migrate:
    image: "go8/migrate"
    container_name: "go8_migrate_e2e"
    restart: "no"
    build:
      context: ../
      dockerfile: e2e/migrate.Dockerfile
    entrypoint: ["/usr/local/bin/migrate"]
    environment:
      - DB_USER=go8_e2e_user
      - DB_PASS=go8_e2e_pass
      - DB_NAME=go8_e2e_db
    depends_on:
      - postgres

  e2e:
    image: "go8/e2e"
    container_name: "go8_e2e_test"
    restart: "no"
    build:
      context: ../
      dockerfile: e2e/e2e.Dockerfile
    entrypoint: ["/usr/local/bin/end_to_end"]
    environment:
      - DB_USER=go8_e2e_user
      - DB_PASS=go8_e2e_pass
      - DB_NAME=go8_e2e_db
    depends_on:
      - postgres
      - migrate
      - server
