# Examples of using this book API
# for vscode users, install `REST Client` to use these example.

### Create a new book
# curl --location --request POST 'http://localhost:3080/api/v1/book' --header 'Content-Type: application/json' --data-raw '{"title": "Test title","image_url": "https://example.com","published_date": "2020-07-31T15:04:05.123499999Z","description": "test description"}'
POST http://localhost:3080/api/v1/book
Content-Type: application/json

{
  "title": "Test Title",
  "image_url": "https://example.com",
  "published_date": "2020-07-31T15:04:05.123499999Z",
  "description": "test description"
}


### List all books, by default gets the first 10 books when ordered desc
# curl --location --request GET 'http://localhost:3080/api/v1/book'
GET http://localhost:3080/api/v1/book
Accept: application/json


### List paginated books
# curl --location --request GET 'http://localhost:3080/api/v1/book?page=2&size=10'
GET http://localhost:3080/api/v1/book?page=1&size=10
Accept: application/json


### Get one book
# curl --location --request POST 'http://localhost:3080/api/v1/book/1
GET http://localhost:3080/api/v1/book/1
Accept: application/json


### Updates a new book
# curl --location --request PUT 'http://localhost:3080/api/v1/book' --header 'Content-Type: application/json' --data-raw '{"title": "dsgs","image_url": "http://example.com","published_date": "2020-07-31T15:04:05.123499999Z","description": "test descr updated"}'
PUT  http://localhost:3080/api/v1/book/1
Content-Type: application/json

{
  "title": "Test Title 1",
  "image_url": "https://example.com",
  "published_date": "2020-07-31T15:04:05.123499999Z",
  "description": "Test Description updated"
}


### Delete a book
# curl --location --request DELETE 'http://localhost:3080/api/v1/book/1
DELETE http://localhost:3080/api/v1/book/1
Accept: application/json
