// Code generated by mirip; DO NOT EDIT.
// github.com/gmhafiz/mirip

package repository

import (
	"context"
	"github.com/gmhafiz/go8/ent/gen"
	"github.com/gmhafiz/go8/internal/domain/author"
)

// AuthorRedisServiceMock is a mock implementation of AuthorRedisService.
type AuthorRedisServiceMock struct {
	DeleteFunc func(ctx context.Context, id uint) error
	ListFunc   func(ctx context.Context, f *author.Filter) ([]*gen.Author, int, error)
	UpdateFunc func(ctx context.Context, toAuthor *author.Update) (*gen.Author, error)
}

func (m *AuthorRedisServiceMock) Delete(ctx context.Context, id uint) error {
	return m.DeleteFunc(ctx, id)
}

func (m *AuthorRedisServiceMock) List(ctx context.Context, f *author.Filter) ([]*gen.Author, int, error) {
	return m.ListFunc(ctx, f)
}

func (m *AuthorRedisServiceMock) Update(ctx context.Context, toAuthor *author.Update) (*gen.Author, error) {
	return m.UpdateFunc(ctx, toAuthor)
}
